# coding: utf-8

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# coding: utf-8

"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: dev@airflow.apache.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import airflow_client
from airflow_client.models.relative_delta import RelativeDelta  # noqa: E501
from airflow_client.rest import ApiException

class TestRelativeDelta(unittest.TestCase):
    """RelativeDelta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RelativeDelta
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = airflow_client.models.relative_delta.RelativeDelta()  # noqa: E501
        if include_optional :
            return RelativeDelta(
                type = '0', 
                years = 56, 
                months = 56, 
                days = 56, 
                leapdays = 56, 
                hours = 56, 
                minutes = 56, 
                seconds = 56, 
                microseconds = 56, 
                year = 56, 
                month = 56, 
                day = 56, 
                hour = 56, 
                minute = 56, 
                second = 56, 
                microsecond = 56
            )
        else :
            return RelativeDelta(
                type = '0',
                years = 56,
                months = 56,
                days = 56,
                leapdays = 56,
                hours = 56,
                minutes = 56,
                seconds = 56,
                microseconds = 56,
                year = 56,
                month = 56,
                day = 56,
                hour = 56,
                minute = 56,
                second = 56,
                microsecond = 56,
        )

    def testRelativeDelta(self):
        """Test RelativeDelta"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
