# coding: utf-8

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# coding: utf-8

"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: dev@airflow.apache.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import airflow_client
from airflow_client.api.task_instance_api import TaskInstanceApi  # noqa: E501
from airflow_client.rest import ApiException


class TestTaskInstanceApi(unittest.TestCase):
    """TaskInstanceApi unit test stubs"""

    def setUp(self):
        self.api = airflow_client.api.task_instance_api.TaskInstanceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_extra_links(self):
        """Test case for get_extra_links

        Get extra links for task instance  # noqa: E501
        """
        pass

    def test_get_log(self):
        """Test case for get_log

        Get logs for a task instance  # noqa: E501
        """
        pass

    def test_get_task_instance(self):
        """Test case for get_task_instance

        Get a task instance  # noqa: E501
        """
        pass

    def test_get_task_instances(self):
        """Test case for get_task_instances

        Get a list of task instance of DAG.  # noqa: E501
        """
        pass

    def test_get_task_instances_batch(self):
        """Test case for get_task_instances_batch

        Get list of task instances from all DAGs and DAG Runs.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
